app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required


class PitchForm(FlaskForm):
    title = StringField('Pitch Title')
    category = SelectField(u'Pitch Category', choices=[('life', 'life'), ('coding', 'coding'), ('funny', 'funny')])
    pitch = TextAreaField('Pitch')
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):

    comment = TextAreaField('Comment')
    submit = SubmitField('Post Comments')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views,error

app/main/views.py
from flask import render_template
from flask import render_template,request,redirect,url_for
from flask_login import login_required,current_user
from ..models import Pitches, User, Comments
from . import main
from .. import db,photos
from .forms import PitchForm,CommentForm, UpdateProfile


@main.route('/')
def index():
    '''
    my index page
    return
    '''
    message= "Hello"
    title= 'Pitch It Ip!'
    return render_template('index.html', message=message,title=title)

@main.route('/pitch/', methods = ['GET','POST'])
@login_required
def new_pitch():

    form = PitchForm()

    if form.validate_on_submit():
        category = form.category.data
        pitch= form.pitch.data
        title=form.title.data

        # Updated pitchinstance
        new_pitch = Pitches(title=title,category= category,pitch= pitch,user_id=current_user.id)

        title='New Pitch'

        new_pitch.save_pitch()

        return redirect(url_for('main.index'))

    return render_template('pitch.html',pitch_entry= form)

@main.route('/categories/<cate>')
def category(cate):
    '''
    function to return the pitches by category
    '''
    category = Pitches.get_pitches(cate)
    # print(category)
    title = f'{cate}'
    return render_template('categories.html',title = title, category = category)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(author = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(author = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.author))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(author = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/comments/<id>')
@login_required
def comment(id):
    '''
    function to return the comments
    '''
    comm =Comments.get_comment(id)
    print(comm)
    title = 'comments'
    return render_template('comments.html',comment = comm,title = title)

@main.route('/new_comment/<int:pitches_id>', methods = ['GET', 'POST'])
@login_required
def new_comment(pitches_id):
    pitches = Pitches.query.filter_by(id = pitches_id).first()
    form = CommentForm()

    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comments(comment=comment,user_id=current_user.id, pitches_id=pitches_id)


        new_comment.save_comment()


        return redirect(url_for('main.index'))
    title='New Pitch'
    return render_template('new_comment.html',title=title,comment_form = form,pitches_id=pitches_id)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
 <head>
   <meta charset="utf-8">
   {% if title %}
   <title>{{ title }}</title>
   {% else %}
   <title>Pitch It Up!! </title>
   {% endif %}
 </head>
 <body>

   {% block content %}

   {% endblock %}

 </body>
</html>

app/templates/categories.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/categories.css')}}"> {% endblock %}
<br>
<br>
<br>
<br>

<body>
  {% block content %}
  <br>
  <br>
  <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Add Pitch</a></button>
  <div class="container">
    <div class="card-columns">
      {% for category in category[::-1] %}

      <div class="card bg-transparent border-success">
        <div class="card-header bg-transparent border-success">
          {{category.title}}
        </div>
        <div class="card-body text">
          <blockquote class="blockquote mb-0">
            <p>{{category.pitch}}</p><br>
            <footer class="blockquote-footer bg-transparent border-success">{{category.author}}
              <br><cite title="Source Title">Publish date: {{category.date.strftime('%Y-%m-%d')}}</cite></footer>
          </blockquote>
        </div>
        <div class="card-footer bg-transparent border-success">
          <button type="button" class="btn btn-outline-success btn-sm"><a href="/new_comment/{{category.id}}">Comment</a></button> <button type="button" class="btn btn-outline-success btn-sm"><a href="/comments/{{category.id}}">View comments</a></button></div>
      </div>

      {% endfor %}
      
    </div>
    {% endblock %}
</body>

app/templates/comments.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<br>
<br>

<body>
  {% for comm in comment[::-1] %}
  <div class="container">
    <div class="card-groups">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">{{comm.author}}</h4>
          <p class="card-text">{{comm.comment}}.</p>
        </div>
        <div class="card-footer bg-transparent border-success"><small class="text-muted">Publish date:{{comm.date_posted.strftime('%Y-%m-%d')}}</small></div>
      </div>
    </div>
  </div>

  {% endfor %}

  {% endblock %}
</body>

app/templates/fourOhfour.html
{% extends 'base.html'%}

{% block content %}
<br>
<br>
    <h1>Sorry! we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}"> {% endblock %}
{% block content %}

<body>
  <br>
  <div class="d-flex justify-content-center">
    <div class="card-groups">
      <div class="card border-info mb-3" style="max-width: 35rem;">
        <div class="card-header">Life</div>
        <div class="card-body text-info">
          <h5 class="card-title">Pitches about life</h5>
          <p class="card-text">Want to change peoples mindsets, then give a pitch on best life practices!!</p>
          <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Add Pitch</a></button>
          <button type="button" class="btn btn-outline-primary"><a href="/categories/life">Read Pitches</a></button>
        </div>
      </div>

      <div class="card border-info mb-3" style="max-width: 35rem;">
        <div class="card-header">Coding</div>
        <div class="card-body text-info">
          <h5 class="card-title">Pitches about coding</h5>
          <p class="card-text">Want to change peoples mindsets, then give a pitch on best coding practices!!</p>
          <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Add Pitch</a></button>
          <button type="button" class="btn btn-outline-primary"><a href="/categories/coding">Read Pitches</a></button>
        </div>
      </div>

      <div class="card border-info mb-3" style="max-width: 35rem;">
        <div class="card-header">Funny</div>
        <div class="card-body text-info">
          <h5 class="card-title">Funny Pitches</h5>
          <p class="card-text">Want to change peoples mindsets, then give a pitch on how best to make things fun!!</p>
          <button type="button" class="btn btn-outline-primary"><a href="../pitch/">Add Pitch</a></button>
          <button type="button" class="btn btn-outline-primary"><a href="/categories/funny">Read Pitches</a></button>
        </div>
      </div>

    </div>
  </div>

  {% endblock%}
</body>

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="/">Pitch It Up</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/categories/life">Life</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/categories/coding">Coding</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/categories/funny">Funny</a>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      {% if current_user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('main.profile',uname=current_user.author)}}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.logout')}}">Sign out</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('auth.login')}}">Sign in</a>
      </li>
      {%endif%}
    </ul>
  </div>
</nav>

app/templates/new_comment.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<br>
<br>
<div class="container">
<br>
<br>
  {{ wtf.quick_form(comment_form) }}


</div>



{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<br>
<br>
<div class="container">
<br>
<br>
  {{ wtf.quick_form(pitch_entry) }}


</div>



{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
{% if user == current_user %}

{% endif %}
<br>
<br>
<div class="container">
  <div class="row">
    <!-- displaying  Username-->
    <div class="col-md-4">
      <h3>Author:  {{user.author| capitalize}} </h3>
      <br>
      <hr>
      <a href="{{url_for('main.update_profile',uname=user.author)}}">Edit profile</a>
      <!--Displaying user bio-->
      {% if user.bio %}
      <br>
      <h4>{{user.bio}}</h4>
      {%else%}
      <br>
      <p> {{user.author| capitalize}} has no bio </p>
      {% endif %}
    </div>

    <!--Display profile photo-->
    <div class="col-md-8">
      {% if user.profile_pic_path %}

      <div class="card">
         <img class="card" src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" height=50%>
      </div>
      <div class="row">
        {%else%}

        <h3><strong>No profile picture</strong></h3>

        {% endif %}

        {% if user == current_user %}
        <form action="{{url_for('main.update_pic',uname=user.author)}}" method="post" enctype="multipart/form-data">
          <br>
          <input type="file"  name="photo" class="form-control" required>
          <br>
          <input type="submit">







      </form>
        {% endif %}
      </div>
    </div>
  </div>
  {% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}